version: '3.8'

services:
  mi-servidor-node:
    build: .
    container_name: express_app
    restart: unless-stopped
    ports:
      - "5000:5000" # Mapea el puerto 3000 del servidor al 3000 del contenedor
    environment:
      - NODE_ENV=production